server:
port: 8080

spring:
    application:
        name: api-gateway
    main:
        web-application-type: reactive
    cloud:
        gateway: 
            discovery:
                locator:
                    enable: true
                    lower-case-service-id: true
    output: 
        ansi:
            enabled: ALWAYS 

eureka:
    client: 
        service-url:
            defaultZone: http://localhost:8761/eureka/
        fetch-registry: true
        register-with-eureka: true

logging:
    pattern: 
        console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
    level:
        org.springframework.cloud.netflix: DEBUG
        com.netflix: DEBUG